import {
  ColorSchemeScript,
  createTheme,
  MantineProvider,
  mantineHtmlProps,
} from "@mantine/core";
import type { Metadata } from "next";
import { Martian_Mono } from "next/font/google";
import { AppShell } from "@/shared/components/layout";

import "@mantine/core/styles.css";
import "./globals.css";

const mainFont = Martian_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-martian-mono",
});

const theme = createTheme({
  fontFamily: "var(--font-martian-mono), monospace",
  fontFamilyMonospace: "var(--font-martian-mono), monospace",
  headings: { fontFamily: "var(--font-martian-mono), monospace" },
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pl"
      className={`${mainFont.variable} antialiased`}
      {...mantineHtmlProps}
    >
      <head>
        <ColorSchemeScript defaultColorScheme="dark" />
      </head>
      <body>
        <MantineProvider theme={theme} defaultColorScheme="dark">
          <AppShell>{children}</AppShell>
        </MantineProvider>
      </body>
    </html>
  );
}
